auto_backup:
  enabled: false
  interval: 1 # every day
  max_tries: 0 # 0=infinity
  files:
    - /root/brain.nn
    - /root/brain.json
    - /root/.api-report.json
    - /root/handshakes/
    - /root/peers/
    - /etc/pwnagotchi/
    - /var/log/pwnagotchi.log
  commands:
    - "tar czf /tmp/pwnagotchi-backup.tar.gz {files}"
    - "mv /tmp/backup.tar.gz /home/pi/pwnagotchi_backup-$(date +%s).tar.gz"
    - "mv /tmp/backup.tar.gz /root/pwnagotchi_backup-$(date +%s).tar.gz"
