main.plugins.banthex.enabled = false
main.plugins.banthex.api_key = "your gnerated api_key here"
main.plugins.banthex.api_url = "https://banthex.de/wpa/"
main.plugins.banthex.download_results = true
main.plugins.banthex.whitelist = [
 "B33zH1v3!",
 "Downtown-Personeel-2.4G",
 "Downtown-Personeel-5G",
 "Downtown-Gasten",
 "2C:3A:FD:42:88:60",
 "2C:3A:FD:42:88:61",
 "BC:05:43:13:6F:82",
 "DownTown Internet"
]