main.name = "WifiKirby"
main.lang = "en"
main.confd = "/etc/pwnagotchi/conf.d/"
main.custom_plugins = "/home/pi/pwnagotchi-plugins-contrib"
main.custom_plugin_repos = [
  "https://github.com/evilsocket/pwnagotchi-plugins-contrib/archive/master.zip",
  "https://github.com/itsdarklikehell/pwnagotchi-plugins/archive/master.zip",
  "https://github.com/c-nagy/pwnagotchi-display-password-plugin/archive/master.zip",
  "https://github.com/xfox64x/pwnagotchi_plugins/archive/master.zip",
  "https://github.com/dadav/pwnagotchi-custom-plugins/archive/master.zip",
  "https://github.com/c-nagy/pwnagotchi-educational-purposes-only-plugin/archive/master.zip",
  "https://github.com/flamebarke/DiscoHash/archive/master.zip",
  "https://github.com/Teraskull/pwnagotchi-community-plugins/archive/master.zip",
  "https://github.com/kellertk/pwnagotchi-plugin-gpsd/archive/master.zip",
  "https://github.com/sixt0o/f0xtr0t/archive/master.zip",
  "https://github.com/LoganMD/pwnagotchi-clock/archive/master.zip",
  "https://github.com/xenDE/pwnagotchi-plugin-webgpsmap/archive/master.zip",
  "https://github.com/PwnPeter/pwnagotchi-plugins/archive/master.zip",
  "https://github.com/diytechtinker/pwnagotchi_plugins/archive/master.zip",
  "https://github.com/crahan/pwnagotchi-plugins/archive/master.zip",
  "https://github.com/ThaFresh/pwnplugins/archive/master.zip",
  "https://github.com/tjbishop07/pwnagotchi-plugins/archive/master.zip",
  "https://github.com/allordacia/Pwnagotchi-Handshaker/archive/master.zip",
  "https://github.com/iggdawg/pwnagotchi_plugins/archive/master.zip",
  "https://github.com/wpa-2/telegram.py/archive/master.zip",
  "https://github.com/xenDE/pwnagotchi-plugin-sound/archive/master.zip",
  "https://github.com/BradlySharpe/pwnagotchi-plugins/archive/master.zip",
  "https://github.com/nobbs/pwnagotchi-nextcloud/archive/master.zip",
  "https://github.com/GlennPegden2/privacy-nightmare-pwnagotchi-plugin/archive/master.zip",
  "https://github.com/do-ki/custom-plugins/archive/master.zip",
  "https://github.com/Apadgett879/glowing-chainsaw/archive/master.zip",
  "https://github.com/IdolonInMachina/pwnagotchi-plugins/archive/master.zip",
  "https://github.com/Sniffleupagus/pwnagotchi_plugins/archive/master.zip",
  "https://github.com/chrislovessushi/better-button-shim-pwnagotchi/archive/master.zip",
  "https://github.com/jjensn/hashespwnagotchi/archive/master.zip",
  "https://github.com/mikebush92/pwnagotchi-plugins/archive/master.zip",
  "https://github.com/SilenTree12th/pwnagotchi_plugins/archive/master.zip",
  "https://github.com/wraydar/pwnagotchi-custom-plugins/archive/master.zip",
  "https://github.com/KingyZhara/Pwnagotchi-Plugins-Zhara/archive/master.zip",
  "https://github.com/RasTacsko/Pwnagotchi-workinprogress/archive/master.zip"
]
main.iface = "mon0"
main.mon_start_cmd = "/usr/bin/monstart"
main.mon_stop_cmd = "/usr/bin/monstop"
main.mon_max_blind_epochs = 50
main.no_restart = false
main.whitelist = [
 "B33zH1v3!",
 "Downtown-Personeel-2.4G",
 "Downtown-Personeel-5G",
 "Downtown-Gasten",
 "2C:3A:FD:42:88:60",
 "2C:3A:FD:42:88:61",
 "BC:05:43:13:6F:82",
 "DownTown Internet"
]
main.filter = ""

main.plugins.grid.enabled = true
main.plugins.grid.report = false
main.plugins.grid.exclude = [
 "B33zH1v3!",
 "Downtown-Personeel-2.4G",
 "Downtown-Personeel-5G",
 "Downtown-Gasten",
 "2C:3A:FD:42:88:60",
 "2C:3A:FD:42:88:61",
 "BC:05:43:13:6F:82",
 "DownTown Internet"
]

main.plugins.auto-update.enabled = true
main.plugins.auto-update.install = true
main.plugins.auto-update.interval = 1

main.plugins.net-pos.enabled = true
main.plugins.net-pos.api_key = "test"

main.plugins.gps.enabled = false
main.plugins.gps.speed = 19200
main.plugins.gps.device = "/dev/ttyUSB0"

main.plugins.webgpsmap.enabled = true

main.plugins.onlinehashcrack.enabled = true
main.plugins.onlinehashcrack.email = "bauke.molenaar@gmail.com"
main.plugins.onlinehashcrack.dashboard = ""
main.plugins.onlinehashcrack.single_files = true
main.plugins.onlinehashcrack.whitelist = [
 "B33zH1v3!",
 "Downtown-Personeel-2.4G",
 "Downtown-Personeel-5G",
 "Downtown-Gasten",
 "2C:3A:FD:42:88:60",
 "2C:3A:FD:42:88:61",
 "BC:05:43:13:6F:82",
 "DownTown Internet"
]

main.plugins.wpa-sec.enabled = true
main.plugins.wpa-sec.api_key = "4ce5559bbb9c3852a0c3ac3652836aa0"
main.plugins.wpa-sec.api_url = "https://wpa-sec.stanev.org/?my_nets"
main.plugins.wpa-sec.download_results = true
main.plugins.wpa-sec.whitelist = [
 "B33zH1v3!",
 "Downtown-Personeel-2.4G",
 "Downtown-Personeel-5G",
 "Downtown-Gasten",
 "2C:3A:FD:42:88:60",
 "2C:3A:FD:42:88:61",
 "BC:05:43:13:6F:82",
 "DownTown Internet"
]

main.plugins.wigle.enabled = true
main.plugins.wigle.api_key = "QUlEN2VlZGZkYWU1ODQ1NzJhYzEyODdmMGY2YjQ0OTc5NDY6Zjc3OTZmMjFiMjhhMjE5MTMwMjczNWQ1NDA0YWFiMWM"
main.plugins.wigle.whitelist = [
 "B33zH1v3!",
 "Downtown-Personeel-2.4G",
 "Downtown-Personeel-5G",
 "Downtown-Gasten",
 "2C:3A:FD:42:88:60",
 "2C:3A:FD:42:88:61",
 "BC:05:43:13:6F:82",
 "DownTown Internet"
]
main.plugins.wigle.donate = true

main.plugins.bt-tether.enabled = true

main.plugins.bt-tether.devices.android-phone.enabled = true
main.plugins.bt-tether.devices.android-phone.search_order = 1
main.plugins.bt-tether.devices.android-phone.mac = "DC:E5:5B:06:A5:EC"
main.plugins.bt-tether.devices.android-phone.ip = "192.168.44.44"
main.plugins.bt-tether.devices.android-phone.netmask = 24
main.plugins.bt-tether.devices.android-phone.interval = 1
main.plugins.bt-tether.devices.android-phone.scantime = 10
main.plugins.bt-tether.devices.android-phone.max_tries = 0
main.plugins.bt-tether.devices.android-phone.share_internet = true
main.plugins.bt-tether.devices.android-phone.priority = 1

main.plugins.bt-tether.devices.ios-phone.enabled = false
main.plugins.bt-tether.devices.ios-phone.search_order = 2
main.plugins.bt-tether.devices.ios-phone.mac = ""
main.plugins.bt-tether.devices.ios-phone.ip = "172.20.10.6"
main.plugins.bt-tether.devices.ios-phone.netmask = 24
main.plugins.bt-tether.devices.ios-phone.interval = 5
main.plugins.bt-tether.devices.ios-phone.scantime = 20
main.plugins.bt-tether.devices.ios-phone.max_tries = 0
main.plugins.bt-tether.devices.ios-phone.share_internet = false
main.plugins.bt-tether.devices.ios-phone.priority = 999

main.plugins.memtemp.enabled = false
main.plugins.memtemp.scale = "celsius"
main.plugins.memtemp.orientation = "horizontal"

main.plugins.paw-gps.enabled = true
main.plugins.paw-gps.ip = "192.168.44.1:8080"

main.plugins.gpio_buttons.enabled = false

main.plugins.led.enabled = true
main.plugins.led.led = 0
main.plugins.led.delay = 200
main.plugins.led.patterns.loaded = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.updating = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.unread_inbox = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.ready = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.ai_ready = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.ai_training_start = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.ai_best_reward = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.ai_worst_reward = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.bored = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.sad = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.excited = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.lonely = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.rebooting = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.wait = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.sleep = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.wifi_update = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.association = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.deauthentication = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.handshake = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.epoch = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.peer_detected = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led.patterns.peer_lost = "oo  oo  oo oo  oo  oo  oo"

main.plugins.logtail.enabled = false
main.plugins.logtail.max-lines = 10000

main.log.path = "/var/log/pwnagotchi.log"
main.log.rotation.enabled = true
main.log.rotation.size = "10M"

ai.enabled = true
ai.path = "/root/brain.nn"
ai.laziness = 0.1
ai.epochs_per_episode = 50

ai.params.gamma = 0.99
ai.params.n_steps = 1
ai.params.vf_coef = 0.25
ai.params.ent_coef = 0.01
ai.params.max_grad_norm = 0.5
ai.params.learning_rate = 0.001
ai.params.alpha = 0.99
ai.params.epsilon = 0.00001
ai.params.verbose = 1
ai.params.lr_schedule = "constant"

personality.advertise = true
personality.deauth = true
personality.associate = true
personality.channels = []
personality.min_rssi = -200
personality.ap_ttl = 120
personality.sta_ttl = 300
personality.recon_time = 30
personality.max_inactive_scale = 2
personality.recon_inactive_multiplier = 2
personality.hop_recon_time = 10
personality.min_recon_time = 5
personality.max_interactions = 3
personality.max_misses_for_recon = 5
personality.excited_num_epochs = 10
personality.bored_num_epochs = 15
personality.sad_num_epochs = 25
personality.bond_encounters_factor = 20000

ui.fps = 0.0
ui.font.name = "DejaVuSansMono" # for japanese: fonts-japanese-gothic
ui.font.size_offset = 0 # will be added to the font size

ui.faces.look_r = "( ⚆_⚆)"
ui.faces.look_l = "(☉_☉ )"
ui.faces.look_r_happy = "( ◕‿◕)"
ui.faces.look_l_happy = "(◕‿◕ )"
ui.faces.sleep = "(⇀‿‿↼)"
ui.faces.sleep2 = "(≖‿‿≖)"
ui.faces.awake = "(◕‿‿◕)"
ui.faces.bored = "(-__-)"
ui.faces.intense = "(°▃▃°)"
ui.faces.cool = "(⌐■_■)"
ui.faces.happy = "(•‿‿•)"
ui.faces.excited = "(ᵔ◡◡ᵔ)"
ui.faces.grateful = "(^‿‿^)"
ui.faces.motivated = "(☼‿‿☼)"
ui.faces.demotivated = "(≖__≖)"
ui.faces.smart = "(✜‿‿✜)"
ui.faces.lonely = "(ب__ب)"
ui.faces.sad = "(╥☁╥ )"
ui.faces.angry = "(-_-')"
ui.faces.friend = "(♥‿‿♥)"
ui.faces.broken = "(☓‿‿☓)"
ui.faces.debug = "(#__#)"
ui.faces.upload = "(1__0)"
ui.faces.upload1 = "(1__1)"
ui.faces.upload2 = "(0__1)"

ui.web.enabled = true
ui.web.address = "0.0.0.0"
ui.web.username = "rizzo"
ui.web.password = "Crims0nDynam0!"
ui.web.origin = ""
ui.web.port = 8080
ui.web.on_frame = "pwnagotchi-viewer-next"

ui.display.enabled = false
ui.display.rotation = 180
ui.display.type = "waveshare_2"
ui.display.color = "black"

bettercap.scheme = "http"
bettercap.hostname = "localhost"
bettercap.port = 8081
bettercap.username = "rizzo"
bettercap.password = "Crims0nDynam0!"
bettercap.handshakes = "/root/handshakes"
bettercap.silence = [
 "ble.device.new",
 "ble.device.lost",
 "ble.device.disconnected",
 "ble.device.connected",
 "ble.device.service.discovered",
 "ble.device.characteristic.discovered",
 "wifi.client.new",
 "wifi.client.lost",
 "wifi.client.probe",
 "wifi.ap.new",
 "wifi.ap.lost",
 "mod.started",
]

fs.memory.enabled = false
fs.memory.mounts.log.enabled = false
fs.memory.mounts.log.mount = "/var/log"
fs.memory.mounts.log.size = "50M"
fs.memory.mounts.log.sync = 60
fs.memory.mounts.log.zram = true
fs.memory.mounts.log.rsync = true

fs.memory.mounts.data.enabled = false
fs.memory.mounts.data.mount = "/var/tmp/pwnagotchi"
fs.memory.mounts.data.size = "10M"
fs.memory.mounts.data.sync = 3600
fs.memory.mounts.data.zram = false
fs.memory.mounts.data.rsync = true