led:
  enabled: true
  led: 0
  delay: 200
  patterns.loaded: "oo  oo  oo oo  oo  oo  oo"
  patterns.updating: "oo  oo  oo oo  oo  oo  oo"
  patterns.unread_inbox: "oo  oo  oo oo  oo  oo  oo"
  patterns.ready: "oo  oo  oo oo  oo  oo  oo"
  patterns.ai_ready: "oo  oo  oo oo  oo  oo  oo"
  patterns.ai_training_start: "oo  oo  oo oo  oo  oo  oo"
  patterns.ai_best_reward: "oo  oo  oo oo  oo  oo  oo"
  patterns.ai_worst_reward: "oo  oo  oo oo  oo  oo  oo"
  patterns.bored: "oo  oo  oo oo  oo  oo  oo"
  patterns.sad: "oo  oo  oo oo  oo  oo  oo"
  patterns.excited: "oo  oo  oo oo  oo  oo  oo"
  patterns.lonely: "oo  oo  oo oo  oo  oo  oo"
  patterns.rebooting: "oo  oo  oo oo  oo  oo  oo"
  patterns.wait: "oo  oo  oo oo  oo  oo  oo"
  patterns.sleep: "oo  oo  oo oo  oo  oo  oo"
  patterns.wifi_update: "oo  oo  oo oo  oo  oo  oo"
  patterns.association: "oo  oo  oo oo  oo  oo  oo"
  patterns.deauthentication: "oo  oo  oo oo  oo  oo  oo"
  patterns.handshake: "oo  oo  oo oo  oo  oo  oo"
  patterns.epoch: "oo  oo  oo oo  oo  oo  oo"
  patterns.peer_detected: "oo  oo  oo oo  oo  oo  oo"
  patterns.peer_lost: "oo  oo  oo oo  oo  oo  oo"
